---
title: "TP2"
format: html
editor: visual
---

```{r, message=FALSE}
 library(dplyr)

#graphique 
library(ggplot2)
install.packages("plotly")
library(plotly)

#format date 
library(lubridate)

```

premier graphique à partir de mpg

```{r}

mpg <- mpg

str(mpg)
```

```{r}
ggplot(data = mpg,
        mapping = aes(x = displ, y = hwy)) + 
  geom_point() + 
  labs(title = "consommation de carburant vs volume total des cylindres moteur",
       x = "volume total de cylindres (L)",
       y = "Autonomie autoroute (mpg) ")
```

```{r}

ggplot(data = mpg,
       mapping = aes(x = displ, y = hwy, colour = class)) +
  geom_point() + 
  facet_wrap(~class) +
  theme_minimal()+
  labs(title = "comparaison de la conso de carburant selon les types de voiture")
    

```

# Exercice 1

## question 1

```{r}
# ctrl + alt + I
# Alt Gr + 2 
#ctrl + maj + M

data("starwars")

str(starwars)


```
#Q2
```{r}
starwars <- starwars %>% 
  filter(!is.na(height), is.na(mass) == FALSE)

```
#Q3
```{r}

plot(starwars$height, starwars$mass)

```
#Q4

```{r}
ggplot(data = starwars,
       mapping = aes( x = height, y = mass)) +
  geom_point()
```

#Q5

```{r}
g <- ggplot(data = starwars,
       mapping = aes( x = height, y = mass)) +
  geom_point()

ggplotly(g)

```

#Q6 / Q7

 la regression linéaire simple de mass (variable à expliquer) en fonction de height (variable
explicative)
*commment evolue Y quand X change ? * 

```{r}
reg_q6 <- lm(data = starwars,  mass~height )

summary(reg_q6)
```


```{r}
cor(starwars$mass,starwars$height)

```

#Q8 
observation aberrante a été retirée

```{r}
starwars_hors_VA <- starwars %>% filter( mass != max(mass))

ggplot(data = starwars_hors_VA,
       mapping = aes( x= height, y=mass))+
  geom_point()




```

```{r}
reg_q8 <- lm(data  =starwars_hors_VA, mass~height)
summary(reg_q8)
```
#Q9
```{r}

cor(starwars_hors_VA$mass, starwars_hors_VA$height)

```

#Q10
```{r}
ggplot(data = starwars_hors_VA,
       mapping = aes( x= height, y=mass, color= species))+
  geom_point()
  
  
  
  
```
#Q11

```{r}
ggplot(starwars_hors_VA, aes(x = height, y=mass, color =birth_year, shape = sex))+
  geom_point()
```
 package R pour palettes de couleur : RColorBrewer

```{r}
ggplot(starwars_hors_VA, aes(x = height, y=mass, color =birth_year, shape = sex))+
  geom_point()+
  scale_color_manual(values = c("male"="blue", "female"="pink","none"="grey"))
```


#Q12

```{r}
g <- ggplot( data = starwars_hors_VA,
             mapping = aes(x = height, y = mass, color = sex))+
  geom_point()+
  theme_light()+
  labs(title = "pas beacoup de femmmes dans starwars",
       subtitle = "croisement des variables de poids et de taille selon le sexe",
       x = "taille",
       y = "poids",
       source =" source : starwars dplyr")
ggplotly(g)

```



# Exercice 2

##Q1

```{r}
set.seed(2026)

Education <- rbinom(1000,2,0.5)

Y1 <- rnorm(1000, mean = 0, sd=1)
Y2 <- rnorm(1000)


Neuroticism <- Y1 + Education

Salary <- 2*Education + Y2 - Neuroticism*0.1

Education <- factor(Education, levels = c("0","1","2"), labels = c("Low","Medium","High"))

```
##Q3

```{r}
data <- tibble
```









